apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-boot3-migrated-2025-11-21-1444
  description: A Spring Boot 3 application migrated to the latest version, focusing on modern Java features and improved performance.
  annotations:
    github.com/project-slug: Ayush-Singh3/spring-boot3-migrated-2025-11-21-1444
    jira/project-key: SCRUM
    jira/label: backstage-component:spring-boot3-migrated-2025-11-21-1444
spec:
  type: application
  owner: ICS
  lifecycle: experimental